apiVersion: v2
name: wordpress
description: A Helm chart for WordPress with MySQL and Nginx
type: application
version: 1.0.0
appVersion: "6.3"

dependencies:
  - name: mariadb
    version: "11.0.0"
    repository: "https://charts.bitnami.com/bitnami"