apiVersion: v2
name: monitoring
description: A Helm chart for Prometheus and Grafana monitoring
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: kube-prometheus-stack
    version: "48.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"