apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-mysql
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  mysql-root-password: {{ .Values.mariadb.auth.rootPassword | b64enc | quote }}