{{- if .Values.nginx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}-nginx
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    component: nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
      component: nginx
  template:
    metadata:
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
        component: nginx
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/nginx_status"
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          {{- toYaml .Values.nginx.resources | nindent 12 }}
        livenessProbe:
          {{- toYaml .Values.nginx.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.nginx.readinessProbe | nindent 12 }}
        volumeMounts:
        - name: nginx-config
          mountPath: /opt/openresty/nginx/conf/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: {{ include "wordpress.fullname" . }}-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-nginx
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    component: nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
  - port: {{ .Values.nginx.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
    component: nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}-nginx-config
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
  nginx.conf: |
    {{- .Files.Get "files/nginx.conf" | nindent 4 }}
{{- end }}