apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    component: wordpress
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
      component: wordpress
  template:
    metadata:
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
        component: wordpress
    spec:
      containers:
      - name: wordpress
        image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
        imagePullPolicy: {{ .Values.wordpress.image.pullPolicy }}
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Values.wordpress.env.WORDPRESS_DB_HOST }}
        - name: WORDPRESS_DB_USER
          value: {{ .Values.wordpress.env.WORDPRESS_DB_USER }}
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "wordpress.fullname" . }}-mysql
              key: mysql-password
        - name: WORDPRESS_DB_NAME
          value: {{ .Values.wordpress.env.WORDPRESS_DB_NAME }}
        resources:
          {{- toYaml .Values.wordpress.resources | nindent 12 }}
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        livenessProbe:
          {{- toYaml .Values.wordpress.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.wordpress.readinessProbe | nindent 12 }}
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ include "wordpress.fullname" . }}-wordpress-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    component: wordpress
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
    component: wordpress
